# Generated by Django 2.1.3 on 2018-11-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(editable=False, verbose_name='uuid')),
                ('path', models.CharField(max_length=50, verbose_name='path')),
                ('createDateTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'uploadrecord',
                'ordering': ('createDateTime',),
            },
        ),
    ]
