# Generated by Django 2.1.3 on 2018-11-19 20:33

from django.db import migrations, models
import train.models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadrecord',
            name='path',
        ),
        migrations.AddField(
            model_name='uploadrecord',
            name='image',
            field=models.ImageField(default=None, upload_to=train.models.savepath),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadrecord',
            name='uuid',
            field=models.UUIDField(verbose_name='uuid'),
        ),
    ]
