# Generated by Django 2.1.3 on 2018-11-30 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('train', '0003_auto_20181129_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagevertor',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagevertor',
            name='uuid',
            field=models.UUIDField(verbose_name='uuid'),
        ),
    ]
